# Generated by Django 3.1.12 on 2026-04-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('roles', models.JSONField()),
                ('dificultad', models.CharField(max_length=50)),
                ('tipo_dano', models.CharField(max_length=50)),
                ('habilidades', models.JSONField()),
                ('estadisticas', models.JSONField()),
                ('builds', models.JSONField()),
                ('runas', models.JSONField()),
                ('hechizos', models.JSONField()),
                ('matchups', models.JSONField()),
                ('tier', models.CharField(max_length=2)),
                ('parche', models.CharField(max_length=10)),
            ],
        ),
    ]
