# Generated by Django 6.0.4 on 2026-05-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueOfLegends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
