# Generated by Django 6.0.4 on 2026-05-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueOfLegends', '0002_alter_personaje_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='sprite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
