# Generated by Django 6.0.4 on 2026-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueOfLegends', '0003_personaje_icon_personaje_sprite'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='splash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='sprite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
